image:
  repository: ghcr.io/kdiggety/anomaly-scorer
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull

service:
  port: 8080

replicaCount: 1

resources:
  requests: { cpu: "25m", memory: "64Mi" }
  limits:   { cpu: "500m", memory: "256Mi" }
podAnnotations:
  sidecar.istio.io/proxyCPU: "25m"
  sidecar.istio.io/proxyMemory: "64Mi"
  sidecar.istio.io/proxyCPULimit: "250m"
  sidecar.istio.io/proxyMemoryLimit: "128Mi"
  sidecar.istio.io/holdApplicationUntilProxyStarts: "true"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
