apiVersion: v1
kind: Service
metadata:
  name: retriever
  labels: { app: retriever }
spec:
  selector: { app: retriever }
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
