apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
{{- range .Values.gateway.hosts }}
        - "{{ . }}"
{{- end }}
