replicaCount: 1

image:
  repository: ghcr.io/kdiggety/web
  tag: dev
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull

service:
  port: 80

readinessPath: /
livenessPath: /
containerPort: 80
