image:
  repository: ghcr.io/kdiggety/retriever
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 8080
env:
  OPENSEARCH_URL: http://opensearch.ml.svc.cluster.local:9200
  INDEX_NAME: ml-docs
  ANN_FIELD: embedding
  MIN_SCORE: "0.1"
resources:
  requests: { cpu: 200m, memory: 256Mi }
  limits:   { cpu: 1,    memory: 1Gi }
