apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: <ECR_OR_DOCKERHUB>/sample-frontend:<TAG>
          ports:
            - containerPort: 80
