apiVersion: v1
kind: Service
metadata:
  name: anomaly-scorer
  labels: { app: anomaly-scorer }
spec:
  selector: { app: anomaly-scorer }
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
