apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-env
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    oidcIssuerPrimary: "{{ .Values.sealed.apiEnv.oidcIssuerPrimary }}"
    oidcIssuerAlt: "{{ .Values.sealed.apiEnv.oidcIssuerAlt }}"
    oidcAudience: "{{ .Values.sealed.apiEnv.oidcAudience }}"
  template:
    metadata:
      name: api-env
      namespace: {{ .Release.Namespace }}
    type: Opaque
