apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    redisPassword: "{{ .Values.sealed.redisAuth.redisPassword }}"
  template:
    metadata:
      name: redis-auth
      namespace: {{ .Release.Namespace }}
    type: Opaque
