# =============================================================================
# Umbrella values.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# Redis (Bitnami subchart)
# -----------------------------------------------------------------------------
redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      enabled: false                     # dev-friendly; enable in prod overlays
    podAnnotations:
      sidecar.istio.io/inject: "true"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  auth:
    enabled: true
    existingSecret: redis-auth           # materialized from SealedSecret
    existingSecretPasswordKey: redis-password
  networkPolicy:
    enabled: true
    allowExternal: false
  metrics:
    enabled: false

# -----------------------------------------------------------------------------
# API (Node/Express backend) — your chart aliased as `api`
# -----------------------------------------------------------------------------
api:
  image:
    repository: sample-api
    tag: dev
    pullPolicy: IfNotPresent
  replicaCount: 1

  service:
    type: ClusterIP
    port: 80

  # Redis connection contract used by your api chart templates
  redis:
    host: "{{ .Release.Name }}-redis-master"   # e.g., fullstack-redis-master
    port: 6379
    passwordSecretName: redis-auth
    passwordSecretKey: redis-password

  # Optional: if your api chart supports envFromSecrets, this pulls JWT_SECRET
  envFromSecrets:
    - api-env

  # Optional direct env (keep empty unless needed)
  env: []

  probes:
    livenessPath: /healthz
    readinessPath: /readyz

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# -----------------------------------------------------------------------------
# Web (React/Vite frontend) — your chart aliased as `web`
# -----------------------------------------------------------------------------
web:
  image:
    repository: sample-frontend
    tag: dev
    pullPolicy: IfNotPresent
  replicaCount: 1

  service:
    type: ClusterIP
    port: 80

  # If your web chart supports envFromSecrets, this provides API_BASE at runtime.
  # (For Vite build-time vars, still inject with --build-arg in CI when building.)
  envFromSecrets:
    - web-env

  # Optional runtime env fallbacks
  env:
    - name: API_BASE
      value: "/api"

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

# -----------------------------------------------------------------------------
# Istio ingress layer — your chart aliased as `istio`
# -----------------------------------------------------------------------------
istio:
  gateway:
    name: web-gateway
    hosts: ["*"]
    port: 80
  virtualService:
    name: fullstack-routing
    hosts: ["*"]
    gatewayName: web-gateway
    routes:
      web: { prefix: "/", service: web, port: 80 }
      api: { prefix: "/api", service: api, port: 80 }

# -----------------------------------------------------------------------------
# SealedSecrets — your chart aliased as `secrets`
# These ciphertexts are produced by `kubeseal` and render to:
#   - Secret web-env    with key: API_BASE
#   - Secret api-env    with key: JWT_SECRET
#   - Secret redis-auth with key: redis-password
# Commit ciphertext safely; never commit raw secrets.
# -----------------------------------------------------------------------------
secrets:
  sealed:
    webEnv:
      apiBase: "AgAqlr1O8BNEcy5ATJjEGYvc9A2a0ErZ7pWtzozUdG06wgbGI1UTnw3xuoL/JozmhMdE9/dmkH/i9r2l6dY/1faTdcvGyHBhRAzYEqSQrRaTKHd6nd13tTrI9I9baZX6S3GDommU1hK73oT3n7RwQj/nOKwoEwkvPgE2aHlKlHI8FtKAvjGhw2gD3e7rLXMkkWrE1e7BQLJTJwWnk/SkVYP1ORm59llp+T1TstKuKznZe9q2dB9vyGgpxWH4hl38T2LYesRPTDxOWNPtwalh5R2KQ/Sfvn1QKL2Rh93GwSiSzujQ2yJ7UnXCwMWn7WbsxBWeHEst/z07afeh/fIny0qvokMQMI/g30t3zWQXDT5Q0dawFp+Z7nZZFBtfXwDGGHwK2KwyjzQC5oY1Gc2+lG7uYCaluUSvVS2lkaDHsq1JQi3n9M75g4wYd+y95rrDGjtp5U9i7AALiZgct2D9g8iHUr9gzEYDx22PvU9UakqcqNuW0AL1+zT3lud+28L6nds5Aps2+IPW4vWMonLuAy4QMrpYibkn9bKvX5Pmn7e9Hw+mtECl1dmYofEcf+NLSBvYmOAUFdJXuetECbzrrFPZffF/WV+8H3msZ8hzplOafJPS9Arb8AU3TmNj89ENTpFlGjZ2QyzlGJKWZKmS2j9KcPandkRpNIUaMJINCBvHwZFM7MjM+zDI4/oz1o85EUyUvrk8uJ0C5XkJ"
    apiEnv:
      jwtSecret: "AgCPTIHfwQHpNUCosgfczu1vBnYqOpdaCVeDyzChyI6En19z12qDwW58VgKrhzsin1DzP/NXjIczSsXl1cCDQ8oTJnoISjXxozcP0QioM6K2ipLkrIuQVzfphE8GaVVD0PJBQQW7LqEchksr1l6qsNAJdMgEEHkYtB9/2alt1Q9rSqkFUyjGEo24IbjIek2NBzNHsn9YyoOBt6G4zqiwLWfepkedtlaKpHjdHAMVIMmUtEQoNr0pHBSaAjhnNxXtHe8LJbGRbcxw1Rt4PS3u616hH9JVkCpXK3oeOuA9o2MFLhIbLieJnZ4+gujfuOzpvjbn3QV/FS4KkV9CJmamydTFsiKb1o5pC2/7ZFljrasOgUDZItCZ/K0KnylqKxyTXu/QPKKpjDpjPJt+QdqnlcLDc+eBKZRUsY8oW9DVWGP6TNNj5OUo/DhXE6+zUR5aOTzEanR2RrF706lMEQbdhf3TeLi58N2UwtgfThr2Wbw4pCoqfA9Ap+G17KNzlZJ/zAMhm63MS68QaB5TEUr8+N9YqFv0MejwYkYah389OysqU5Y1BnK1UAPT14nstL/4v4mK3BCHSqHwtnoSqWAUOG/Rkcf1U0VKB5jQqQramSAw1GWw6tNmtyEdav7l5d5HBtYt023Wu6UPOPOqmbLPry7Efa+Zoc+vW6PBiSwFAuScU8+YNDa/OxSsUtIx/lq+8fmwxAu/ouGW/+FR"
    redisAuth:
      password: "AgAD95dVNlpltnQcV66sIG5zGEMbXKY8gejr5sOTcw/ZiGv2R5Dk3gko+iuBt/0fP5zHEVHiameLqh+lNsTz/7JsBR1WYPdhwSyysROJR8Ht7PiWCMcf9CHbNDIWI/60UeVclKjMMRjtlTlpwIf6vLhTUnu53bUMUUC4lQAljZrUokrxyr2a4yIQNoyNE7+66lna03oAd1uMg7BGPPBQl8GiEqfJUIP+XfrpwQJKiHV2L5TAxV6nF56PGEu+A9EisotFCsoXPpL1IXDEmX4AP3ZNEcxDNp2jslDgUbBWDQ2DQDQrMbL2en1iMTRpb6XvQeteLHdIXWhlNo6Dau3Gmg5tAE5DGpHfPbkmc04a9y8l4E+XoJkbD4uwgAgV+lvrgg9EjDhBYpxdFx6gLMGj5NeU8P/4KlZN0lWOaGAj+w8g/exzm1znZIj8+4ww+j5mc2WpMqaiqtQCkpoiHY50tz8rU/SdhsNglfm8i25E7uUtvgzQymv0b2MWnEjZN3JnpE0At0vTMhjCTo+qpcJxlUkKKn1BIkN3XIbjbNLmSm4eFpYySTevUYTYGu/3NtsYedzQKEyvp0Jg4vmL5YE61h/thN1V+SIrqrrqLUwOeEqSFNTmYL53E4nIK5+5vjO0lXLNxpg5bgqYWGqKpcQ4+Df6CMHmGxgTCyu14OBW6AfNTMYqBhnZPnZ88xQUPPup30I9VWz/suB+g8D9"
