# Values passed to subcharts
api:
  image:
    repository: sample-api
    tag: dev
  replicaCount: 1

web:
  image:
    repository: sample-frontend
    tag: dev
  replicaCount: 1

istio:
  gateway:
    name: web-gateway
    hosts: ["*"]
    port: 80
  virtualService:
    name: fullstack-routing
    hosts: ["*"]
    gatewayName: web-gateway
    routes:
      web: { prefix: "/", service: web, port: 80 }
      api: { prefix: "/api", service: api, port: 80 }
