apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: api-authn
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: api
  jwtRules:
  - issuer: https://accounts.google.com
    jwksUri: https://www.googleapis.com/oauth2/v3/certs
    forwardOriginalToken: true
  - issuer: accounts.google.com
    jwksUri: https://www.googleapis.com/oauth2/v3/certs
    forwardOriginalToken: true
