image:
  repository: ghcr.io/kdiggety/llm-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

replicaCount: 2
  resources:
    requests: { cpu: "25m", memory: "64Mi" }
    limits:   { cpu: "500m", memory: "256Mi" }
  podAnnotations:
    sidecar.istio.io/proxyCPU: "25m"
    sidecar.istio.io/proxyMemory: "64Mi"
    sidecar.istio.io/proxyCPULimit: "250m"
    sidecar.istio.io/proxyMemoryLimit: "128Mi"
    sidecar.istio.io/holdApplicationUntilProxyStarts: "true"

config:
  provider: bedrock
  allowModels:
    - anthropic.claude-3-5-sonnet
    - gpt-4.1-mini

redis:
  url: redis://fullstack-redis-master.sample.svc.cluster.local:6379

opensearch:
  endpoint: http://opensearch.ml.svc.cluster.local:9200
