name: Deploy Local K8s (Umbrella Helm)

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional image tag override (e.g., v0.1.0 or a commit SHA)"
        required: false

concurrency:
  group: deploy-local
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: [self-hosted, local-k8s]
    env:
      NAMESPACE: sample
      WEB_IMAGE: ghcr.io/${{ github.repository_owner }}/web
      API_IMAGE: ghcr.io/${{ github.repository_owner }}/api
      # Bridge secrets to env so we can safely use them in `if:` via env.*
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      PULL_SECRET_NAME: ghcr-pull

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve base tag (prefer input → release tag → full SHA)
        id: base
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            TAG="${{ github.event.inputs.tag }}"
          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG="${GITHUB_REF_NAME}"
          else
            TAG="${GITHUB_SHA}"
          fi
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo "Base tag: $TAG"

      - name: Show cluster context
        shell: bash
        run: |
          set -euo pipefail
          kubectl config current-context
          kubectl get nodes

      - name: Ensure namespace & sidecar injection
        shell: bash
        run: |
          set -euo pipefail
          kubectl get ns "$NAMESPACE" >/dev/null 2>&1 || kubectl create ns "$NAMESPACE"
          kubectl label ns "$NAMESPACE" istio-injection=enabled --overwrite

      # Optional: authenticate docker client so imagetools inspect can see private GHCR
      - name: Login to GHCR (optional)
        if: ${{ env.GHCR_USERNAME != '' && env.GHCR_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_TOKEN }}

      # Optional: create/refresh imagePullSecret for cluster pulls
      - name: Ensure GHCR imagePullSecret + patch default SA (optional)
        if: ${{ env.GHCR_USERNAME != '' && env.GHCR_TOKEN != '' }}
        shell: bash
        run: |
          set -euo pipefail
          kubectl -n "$NAMESPACE" delete secret "$PULL_SECRET_NAME" --ignore-not-found
          kubectl -n "$NAMESPACE" create secret docker-registry "$PULL_SECRET_NAME" \
            --docker-server=ghcr.io \
            --docker-username="$GHCR_USERNAME" \
            --docker-password="$GHCR_TOKEN"
          # Attach to default SA used by the pods
          kubectl -n "$NAMESPACE" patch serviceaccount default \
            --type merge \
            -p "{\"imagePullSecrets\":[{\"name\":\"${PULL_SECRET_NAME}\"}]}"
          echo "Patched default ServiceAccount with imagePullSecret ${PULL_SECRET_NAME}"

      # Resolve tags per service and fall back to :dev if the exact tag isn't present
      - name: Resolve WEB_TAG and API_TAG with preflight check
        id: tags
        shell: bash
        env:
          BASE_TAG: ${{ steps.base.outputs.TAG }}
        run: |
          set -euo pipefail

          resolve() {
            local image="$1" tag="$2" fallback="$3"
            if docker buildx imagetools inspect "${image}:${tag}" >/dev/null 2>&1; then
              echo "$tag"
            else
              echo "$fallback"
            fi
          }

          WEB_TAG="$(resolve "$WEB_IMAGE" "$BASE_TAG" dev)"
          API_TAG="$(resolve "$API_IMAGE" "$BASE_TAG" dev)"

          echo "WEB_TAG=$WEB_TAG" >> "$GITHUB_OUTPUT"
          echo "API_TAG=$API_TAG" >> "$GITHUB_OUTPUT"
          echo "Using WEB_TAG=$WEB_TAG, API_TAG=$API_TAG"

      - name: Add helm repos
        shell: bash
        run: |
          set -euo pipefail
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Build/fetch subchart deps
        shell: bash
        run: helm dependency build "./helm/chart"

      - name: Helm upgrade (use GHCR images + resolved tags)
        shell: bash
        env:
          WEB_TAG: ${{ steps.tags.outputs.WEB_TAG }}
          API_TAG: ${{ steps.tags.outputs.API_TAG }}
        run: |
          set -euo pipefail

          echo "Rendering (dry-run) to sanity-check values..."
          helm upgrade --install fullstack "./helm/chart" -n "$NAMESPACE" \
            --dry-run --debug \
            --set web.image.repository="$WEB_IMAGE" \
            --set web.image.tag="$WEB_TAG" \
            --set api.image.repository="$API_IMAGE" \
            --set api.image.tag="$API_TAG" \
            >/dev/null

          echo "Applying release..."
          helm upgrade --install fullstack "./helm/chart" \
            --namespace "$NAMESPACE" --create-namespace \
            --dependency-update \
            --set web.image.repository="$WEB_IMAGE" \
            --set web.image.tag="$WEB_TAG" \
            --set api.image.repository="$API_IMAGE" \
            --set api.image.tag="$API_TAG"

      - name: Wait for rollouts
        shell: bash
        run: |
          set -euo pipefail
          kubectl -n "$NAMESPACE" rollout status deploy/api --timeout=300s
          kubectl -n "$NAMESPACE" rollout status deploy/web --timeout=300s
          kubectl -n "$NAMESPACE" get pods -o wide

      - name: Smoke test through Istio
        shell: bash
        run: |
          set -euo pipefail
          kubectl -n istio-system get svc istio-ingressgateway

          kubectl -n istio-system port-forward svc/istio-ingressgateway 8080:80 >/tmp/pf.log 2>&1 &
          PF_PID=$!

          # wait for port-forward
          if command -v nc >/dev/null 2>&1; then
            for i in {1..20}; do nc -z localhost 8080 && break || sleep 0.5; done
          else
            sleep 3
          fi

          echo "== /api/health =="
          curl -fsS "http://localhost:8080/api/health" | tee /tmp/health.json

          echo "== / (frontend first 10 lines) =="
          curl -fsS "http://localhost:8080/" | head -n 10

          kill "$PF_PID" || true

      - name: If failed, dump diagnostics
        if: failure()
        shell: bash
        run: |
          echo "---- Pods ----"
          kubectl -n "$NAMESPACE" get pods -o wide || true
          echo "---- Events (tail) ----"
          kubectl -n "$NAMESPACE" get events --sort-by=.lastTimestamp | tail -n 100 || true
          echo "---- API logs ----"
          kubectl -n "$NAMESPACE" logs deploy/api -c api --tail=200 || true
          echo "---- WEB logs ----"
          kubectl -n "$NAMESPACE" logs deploy/web -c web --tail=200 || true

